### ISSUE TITLE
Permission denied in build environment

### ISSUE THREAD

**Issue by digitalkaoz** [Modernizr/customizr#21]
```
[INFO] > customizr@1.0.0-alpha postinstall /home/jenkins/jobs/xxx-stage-portal-build_and_deploy/workspace/xxx/node_modules/grunt-modernizr/node_modules/customizr
[INFO] > node scripts/postinstall.js
[INFO] 
[INFO] --------------------------------------------------------------------------------------------------------------------------------------------
[INFO] [33mThis postinstall script is a workaround for [1mnpm issue #1341: npm install should recursively check/install dependencies[22m[39m
[INFO] More info can be found here: [4m[36mhttps://github.com/npm/npm/issues/1341[39m[24m
[INFO] Checking for any missing Modernizr dependencies in path: [36m/home/jenkins/jobs/xxx-stage-portal-build_and_deploy/workspace/node_modules/grunt-modernizr/node_modules/customizr/node_modules/modernizr[39m
[INFO] --------------------------------------------------------------------------------------------------------------------------------------------
[INFO] 
[INFO] execvp(): Permission denied
[INFO] 
[INFO] events.js:72
[INFO]         throw er; // Unhandled 'error' event
[INFO]               ^
[INFO] Error: spawn EACCES
[INFO]     at errnoException (child_process.js:988:11)
[INFO]     at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

**Comment by digitalkaoz** [comment]
this script is the problem:

https://github.com/doctyper/customizr/blob/develop/scripts/postinstall.js as it spawns another `npm` which is somehow forbidden (using npm through maven with https://github.com/eirslett/frontend-maven-plugin)

**Comment by digitalkaoz** [comment]
is there a workaround?

**Comment by bradoyler** [comment]
+1

**Comment by jfleblanc** [comment]
+1

**Comment by aghouseh** [comment]
+1

**Comment by digitalkaoz** [comment]
@doctyper any suggestions?

**Comment by rejas** [comment]
Postinstall script was removed with https://github.com/Modernizr/customizr/commit/a49145b535290db817ca71ef1bbfff3b9ef24773 so this shouldnt be a problem anymore
